create table "MEMBER"(
    "NUM" number primary key,
    "MEMBERID" varchar2(100) not null unique,
    "MEMBERPW" varchar2(50) not null,
    "NICKNAME" varchar2(10) unique,
    "DATE" DATE
    );
    
CREATE SEQUENCE "MEMBER_SEQ"
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

INSERT INTO "MEMBER"("NUM", "MEMBERID", "MEMBERPW", "NICKNAME", "DATE")
VALUES ("MEMBER_SEQ".NEXTVAL, 'TAEIN1', '1234', 'TAEIN111', SYSDATE);

INSERT INTO "MEMBER"("NUM", "MEMBERID", "MEMBERPW", "NICKNAME", "DATE")
VALUES ("MEMBER_SEQ".NEXTVAL, 'TAEIN2', '1234', 'TAEIN112', SYSDATE);

INSERT INTO "MEMBER"("NUM", "MEMBERID", "MEMBERPW", "NICKNAME", "DATE")
VALUES ("MEMBER_SEQ".NEXTVAL, 'TAEIN3', '1234', 'TAEIN113', SYSDATE);

COMMIT;